import { Track, TransitionAnalysis } from '../types';

export interface PlaylistExportOptions {
  playlistName?: string;
  includeMetadata?: boolean;
  targetFormat?: 'M3U8' | 'CSV' | 'REKORDBOX_XML' | 'SERATO_CRATE';
  includePortalTileSnippet?: boolean;
}

/**
 * Standard .m3u8 Playlist Generator
 * Formats harmonically auto-sorted sequence for Rekordbox, Serato, Traktor, Engine DJ, and USB drives.
 */
export function exportToM3U8(tracks: Track[], options?: PlaylistExportOptions): string {
  const name = options?.playlistName || 'Set_Architect_Harmonic_Sequence';
  const lines: string[] = [];

  lines.push('#EXTM3U');
  lines.push(`#PLAYLIST:${name}`);
  lines.push(`#EXTREM: Generated by AfroSenses Set Architect (https://afrosenses.co.za)`);
  lines.push(`#EXTREM: Total Tracks: ${tracks.length}`);
  lines.push('');

  tracks.forEach((track, idx) => {
    const duration = track.durationSeconds || 180;
    const keyStr = track.key ? `${track.key.number}${track.key.letter}` : '12A';
    const bpmStr = track.bpm ? track.bpm.toFixed(1) : '124.0';

    // Standard Extended M3U directives recognized by Serato, Traktor, Engine DJ & Rekordbox
    lines.push(`#EXTINF:${Math.round(duration)},${track.artist} - ${track.title}`);
    lines.push(`#EXTREM:POS=${idx + 1}`);
    lines.push(`#EXTREM:CAMELOT=${keyStr}`);
    lines.push(`#EXTREM:BPM=${bpmStr}`);
    lines.push(`#EXTREM:GENRE=${track.genre || 'Afro House'}`);
    lines.push(`#EXTREM:ENERGY=${track.des || 5}`);
    if (track.fileName) {
      lines.push(track.fileName);
    } else {
      lines.push(`/music/${track.artist.replace(/\s+/g, '_')}_-_${track.title.replace(/\s+/g, '_')}.mp3`);
    }
    lines.push('');
  });

  return lines.join('\n');
}

/**
 * Detailed CSV Set Blueprint Generator
 * Outputs comprehensive harmonic progression matrix for printouts, set planning, and spreadsheet analytics.
 */
export function exportToCSV(tracks: Track[], transitions?: TransitionAnalysis[]): string {
  const headers = [
    'Position',
    'Track Title',
    'Artist',
    'BPM',
    'Camelot Key',
    'Tonality',
    'Genre',
    'Energy Score (DES)',
    'Transition Quality',
    'Key Modulation',
    'BPM Delta',
    'Recommended Mix Point',
  ];

  const rows = tracks.map((track, idx) => {
    const nextTransition = transitions?.[idx];
    const pos = (idx + 1).toString();
    const title = `"${(track.title || '').replace(/"/g, '""')}"`;
    const artist = `"${(track.artist || '').replace(/"/g, '""')}"`;
    const bpm = track.bpm ? track.bpm.toFixed(1) : '124.0';
    const camelot = track.key ? `${track.key.number}${track.key.letter}` : '12A';
    const tonality = `"${track.key ? track.key.musicalKey : 'A minor'}"`;
    const genre = `"${(track.genre || 'Afro House').replace(/"/g, '""')}"`;
    const energy = (track.des || 5).toFixed(1);

    let transQuality = 'Initial Track';
    let keyMod = 'N/A';
    let bpmDelta = '0.0';
    let mixPoint = 'Intro Outro Blend';

    if (nextTransition) {
      transQuality = `"${nextTransition.type}"`;
      keyMod = `"${nextTransition.harmonicDistance === 0 ? 'Exact Match' : nextTransition.type}"`;
      bpmDelta = `${nextTransition.bpmDelta > 0 ? '+' : ''}${nextTransition.bpmDelta.toFixed(1)} BPM`;
      mixPoint = `"${nextTransition.suggestedMixZone || 'Extended 32-bar percussion blend'}"`;
    } else if (idx === tracks.length - 1) {
      transQuality = 'Set Peak / Outro Track';
      keyMod = 'Final Track';
    }

    return [
      pos,
      title,
      artist,
      bpm,
      camelot,
      tonality,
      genre,
      energy,
      transQuality,
      keyMod,
      bpmDelta,
      mixPoint,
    ].join(',');
  });

  return [headers.join(','), ...rows].join('\n');
}

/**
 * Rekordbox XML Playlist Generator
 */
export function exportToRekordboxXmlFormat(tracks: Track[], playlistName = 'Set Architect Master Crate'): string {
  const dateStr = new Date().toISOString().split('T')[0];

  const trackEntries = tracks
    .map((t, idx) => {
      const keyStr = t.key ? `${t.key.number}${t.key.letter}` : '12A';
      return `    <TRACK TrackID="${idx + 101}" Name="${t.title}" Artist="${t.artist}" Album="${t.genre || 'Single'}" Genre="${t.genre || 'Afro House'}" Kind="MP3 File" Size="10240000" TotalTime="${t.durationSeconds || 300}" DiscNumber="1" TrackNumber="${idx + 1}" Year="2025" AverageBpm="${t.bpm ? t.bpm.toFixed(2) : '124.00'}" DateAdded="${dateStr}" Tonality="${keyStr}" Location="${t.fileName || `file://localhost/Music/${t.artist}-${t.title}.mp3`}" Comments="Set Architect Harmonic Auto-Sort Pos ${idx + 1}" />`;
    })
    .join('\n');

  const playlistKeys = tracks.map((_, idx) => `      <TRACK Key="${idx + 101}" />`).join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<DJ_PLAYLISTS Version="1.0.0">
  <PRODUCT Name="SetArchitect" Version="1.0.0" Company="AfroSenses" />
  <COLLECTION Entries="${tracks.length}">
${trackEntries}
  </COLLECTION>
  <PLAYLISTS>
    <NODE Type="0" Name="ROOT">
      <NODE Type="1" Name="${playlistName}" Entries="${tracks.length}">
${playlistKeys}
      </NODE>
    </NODE>
  </PLAYLISTS>
</DJ_PLAYLISTS>`;
}

/**
 * AfroSenses Main Portal Embedded Tile Snippet Generator
 * Allows seamless integration into the main AfroSenses portal dashboard.
 */
export function generateAfroSensesPortalEmbedSnippet(appUrl = 'https://afrosenses.co.za/apps/set-architect'): string {
  return `<!-- AfroSenses Portal Embedded Tile Widget -->
<div id="afrosenses-set-architect-tile" style="width:100%; max-width:480px; border-radius:16px; overflow:hidden; background:#0f172a; border:1px solid #1e293b; font-family:monospace; color:#f8fafc; padding:20px;">
  <div style="display:flex; align-items:center; justify-between; margin-bottom:12px;">
    <span style="font-size:12px; font-weight:bold; color:#22d3ee; letter-spacing:0.05em;">SERATO & REKORDBOX HARMONIC ENGINE</span>
    <span style="font-size:10px; background:#1e1b4b; color:#818cf8; padding:2px 8px; border-radius:12px; border:1px solid #3730a3;">v1.0 EXEC</span>
  </div>
  <h3 style="margin:0 0 8px 0; font-size:18px; font-bold; color:#ffffff;">AfroSenses Set Architect</h3>
  <p style="margin:0 0 16px 0; font-size:12px; color:#94a3b8; line-height:1.4;">Automated Camelot wheel key sorter & energy curve optimizer for Afro House & Amapiano DJs.</p>
  <a href="${appUrl}" target="_blank" style="display:inline-block; width:100%; text-align:center; padding:10px 16px; background:linear-gradient(to right, #06b6d4, #2563eb); color:#ffffff; font-weight:bold; border-radius:12px; text-decoration:none; box-shadow:0 4px 14px rgba(6,182,212,0.3);">
    LAUNCH SET ARCHITECT APP
  </a>
</div>`;
}

/**
 * Triggers client-side browser file download
 */
export function downloadPlaylistFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8;` });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
